### ISSUE TITLE
many uim-candwin-qt5 processes running

### ISSUE THREAD

**Issue by tomcat14d** [uim/uim#112] opened 2017-08-23 04:28 UTC
I built the latest revision (ce6b4c7).
I use KDE Plasma 5.
After boot Plasma 5, many uim-candwin-qt5 processes running.
Is this a bug ?

**Comment by dai-vdr** [comment] 2017-08-25 02:01
Qt5 support still under construction but dormant...

**Comment by NaofumiHonda** [comment] 2017-09-30 01:40
As I do not use KDE 5, I cannot say a real cause,  the attached patch may fix the issue.
In Qt5, each process always creates own candidate window instance even if it is not used in future. 
That's why, in qt5 base system, too many candidate window processes are observed.
The attached patch delays a creation of candidate window instance until it is really needed.
Note that, after applying the patch, you may fell a short delay at the first time of appearance of a candidate window because of initialization of the candidate window.

[delay.zip](https://github.com/uim/uim/files/1346017/delay.zip)

**Comment by dai-vdr** [comment] 2017-09-30 11:38
Thank you for your working!

But still many uim-candwin-qt5 processes running with my non KDE 5 environment.
For example, I start IM at juffed (Qt5 editor) and Wireshark (Qt5 network analyzer),
2 processes of uim-candwin-qt5 spawned. Qt5 version is 5.9.1.

P.S. could you please send pull request instead of attatchment if possible?

**Comment by tomcat14d** [comment] 2017-09-30 12:26
To NaofumiHonda san:
Thank you for your comments and patch.

I rebuilt uim applying the patch,  this issue was fixed.
Before applying the patch, about 20 processes of uim-candwin-qt5 were running after starting Plasma 5, but now it is zero. (^_^)

When I start IM at Plasma 5 application such as kate, the process of uim-candwin-qt5 starts normally, and the process is also closed after exiting the application.
(Before applying the patch, the process sometimes remained.)
And I don't feel the delay of display of the candidate window at all.

distribution: PCLinuxOS
Qt5 version: 5.9.1
Plasma 5 version: 5.10.5

**Comment by NaofumiHonda** [comment] 2017-10-01 11:37
Thank you for your quick responses. 
The patch seems to work well as expected.

Dai San:  The intention of patch is NOT to unify all the processes to the unique one,
that is, it is an expected behavior for you to see two processes, 
one for the editor and one for  Wireshark. after you started IM conversions with candidate windows.
The issue is that a candidate window process always starts either you did IM conversion or not.
Even a daemon process invokes the one for the candidate window, as a consequence,
you got many candidate window processes when a KDE like system becomes ready,
that is fixed by this patch.

**Comment by dai-vdr** [comment] 2017-10-01 11:58
Thank you for your explain. I misunderstand it is same as gtk's candwin that has only one process.
I merge your patch and close this now. Thank you again.

**Closed by dai-vdr** 2017-10-01 11:58 UTC
Labels: bug, Qt5
